// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5a46rLN706ThrySnNRdr17GxJ-gp-XVA',
    appId: '1:1094596033088:web:7c86d6ea198828b2187da5',
    messagingSenderId: '1094596033088',
    projectId: 'growcoin-c21b1',
    authDomain: 'growcoin-c21b1.firebaseapp.com',
    storageBucket: 'growcoin-c21b1.firebasestorage.app',
    measurementId: 'G-0KS6X6MQ34',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDERK0c8Z-6gmVyryp2bQvdIeGYxAaQft8',
    appId: '1:1094596033088:android:723dee44da24de59187da5',
    messagingSenderId: '1094596033088',
    projectId: 'growcoin-c21b1',
    storageBucket: 'growcoin-c21b1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIxZurs8HebE6qOyjQK2PXR3LvDt5Z3RQ',
    appId: '1:1094596033088:ios:4ded76f9dac2882b187da5',
    messagingSenderId: '1094596033088',
    projectId: 'growcoin-c21b1',
    storageBucket: 'growcoin-c21b1.firebasestorage.app',
    iosBundleId: 'com.example.growcoins',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIxZurs8HebE6qOyjQK2PXR3LvDt5Z3RQ',
    appId: '1:1094596033088:ios:4ded76f9dac2882b187da5',
    messagingSenderId: '1094596033088',
    projectId: 'growcoin-c21b1',
    storageBucket: 'growcoin-c21b1.firebasestorage.app',
    iosBundleId: 'com.example.growcoins',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5a46rLN706ThrySnNRdr17GxJ-gp-XVA',
    appId: '1:1094596033088:web:39edbb8f70925622187da5',
    messagingSenderId: '1094596033088',
    projectId: 'growcoin-c21b1',
    authDomain: 'growcoin-c21b1.firebaseapp.com',
    storageBucket: 'growcoin-c21b1.firebasestorage.app',
    measurementId: 'G-0L2ZM2Z8EZ',
  );
}
